apiVersion: v1
kind: ConfigMap
metadata:
  name: nutriflow-api
data:
  POSTGRES_URL: jdbc:postgresql://postgres:5432/nutriflow
  MONGODB_URI: mongodb://mongodb:27017/nutriflow
  AWS_REGION: us-east-1

